services:
  ebank-discovery-service:
    build: ./discovery-service
    container_name: ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 5
  ebank-config-service:
    build: ./config-service
    container_name: ebank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
       test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
       interval: 10s
       retries: 5
    environment:
      - DISCOVERY-SERVICE-URL=http://ebank-discovery-service:8761/eureka
    depends_on:
      ebank-discovery-service:
        condition: service_healthy
  ebank-customer-service:
    build: ./customer-service
    container_name: ebank-customer-service
    ports:
      - "9001:9001"
    expose:
      - "9001"
    healthcheck:
       test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
       interval: 10s
       retries: 5
    environment:
      - DISCOVERY-SERVICE-URL=http://ebank-discovery-service:8761/eureka
      - CONFIG-SERVICE-URL=http://ebank-config-service:9999
    depends_on:
      ebank-config-service:
        condition: service_healthy
  ebank-account-service:
    build: ./account-service
    container_name: ebank-account-service
    ports:
      - "9002:9002"
    expose:
      - "9002"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
        interval : 10s
        retries : 4
    environment:
      - DISCOVERY-SERVICE-URL=http://ebank-discovery-service:8761/eureka
      - CONFIG-SERVICE-URL=http://ebank-config-service:9999
    depends_on:
      ebank-config-service:
        condition: service_healthy
#      ebank-customer-service:
#        condition: service_healthy
  ebank-gateway-service:
    build: ./gateway-service
    container_name: ebank-gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    healthcheck:
      test: ["CMD" , "curl" , "-f" , "http://localhost:8888/actuator/health"]
      retries: 7
      interval: 10s
    environment:
      - DISCOVERY-SERVICE-URL=http://ebank-discovery-service:8761/eureka
      - CONFIG-SERVICE-URL=http://ebank-config-service:9999
    depends_on:
      ebank-config-service:
        condition: service_healthy
#      ebank-account-service:
#        condition: service_healthy
  ebank-front-end-service:
    build: ./angular-front-end
    container_name: ebank-front-end-service
    ports:
      - "80:80"
    expose:
      - "80"
