spring:
    cloud:
      gateway:
        routes:
          - id : r1
            uri : http://localhost:9000/
            predicates:
              - Path=/customers/**
          - id : r2
            uri : http://localhost:9001/
            predicates:
              - Path=/accounts/**
    application:
      name: gateway-service
server:
  port: 9002

